name: Build and Push Clang Container Images

on:
  push:
    branches:
      - main
    paths:
      - 'dockerfiles/**'
      - '.github/workflows/build-push.yml'
      - 'versions.txt'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:

          - group: 1
            versions: "9.0.0 9.0.0-rc1 9.0.0-rc2"
          - group: 2
            versions: "9.0.0-rc3 9.0.0-rc4 9.0.0-rc5"
          - group: 3
            versions: "9.0.0-rc6 9.0.1 9.0.1-rc1"
          - group: 4
            versions: "9.0.1-rc2 9.0.1-rc3 10.0.0"
          - group: 5
            versions: "10.0.0-rc1 10.0.0-rc2 10.0.0-rc3"
          - group: 6
            versions: "10.0.0-rc4 10.0.0-rc5 10.0.0-rc6"
          - group: 7
            versions: "10.0.1 10.0.1-rc1 10.0.1-rc2"
          - group: 8
            versions: "10.0.1-rc3 10.0.1-rc4 11.0.0"
          - group: 9
            versions: "11.0.0-rc1 11.0.0-rc2 11.0.0-rc3"
          - group: 10
            versions: "11.0.0-rc4 11.0.0-rc5 11.0.0-rc6"
          - group: 11
            versions: "11.0.1 11.0.1-rc1 11.0.1-rc2"
          - group: 12
            versions: "11.1.0 11.1.0-rc1 11.1.0-rc2"
          - group: 13
            versions: "11.1.0-rc3 12.0.0 12.0.0-rc1"
          - group: 14
            versions: "12.0.0-rc2 12.0.0-rc3 12.0.0-rc4"
          - group: 15
            versions: "12.0.0-rc5 12.0.1 12.0.1-rc1"
          - group: 16
            versions: "12.0.1-rc2 12.0.1-rc3 12.0.1-rc4"
          - group: 17
            versions: "13.0.0 13.0.0-rc1 13.0.0-rc2"
          - group: 18
            versions: "13.0.0-rc3 13.0.0-rc4 13.0.1"
          - group: 19
            versions: "13.0.1-rc1 13.0.1-rc2 13.0.1-rc3"
          - group: 20
            versions: "14.0.0 14.0.0-rc1 14.0.0-rc2"
          - group: 21
            versions: "14.0.0-rc3 14.0.0-rc4 14.0.1"
          - group: 22
            versions: "14.0.2 14.0.3 14.0.4"
          - group: 23
            versions: "14.0.5 14.0.6 15.0.0"
          - group: 24
            versions: "15.0.0-rc1 15.0.0-rc2 15.0.0-rc3"
          - group: 25
            versions: "15.0.1 15.0.2 15.0.3"
          - group: 26
            versions: "15.0.4 15.0.5 15.0.6"
          - group: 27
            versions: "15.0.7 16.0.0 16.0.0-rc1"
          - group: 28
            versions: "16.0.0-rc2 16.0.0-rc3 16.0.0-rc4"
          - group: 29
            versions: "16.0.1 16.0.2 16.0.3"
          - group: 30
            versions: "16.0.4 16.0.5 16.0.6"
          - group: 31
            versions: "17.0.0 17.0.0-rc1 17.0.0-rc2"
          - group: 32
            versions: "17.0.0-rc3 17.0.0-rc4 17.0.1"
          - group: 33
            versions: "17.0.2 17.0.3 17.0.4"
          - group: 34
            versions: "17.0.5 17.0.6 18.1.0"
          - group: 35
            versions: "18.1.0-rc1 18.1.0-rc2 18.1.0-rc3"
          - group: 36
            versions: "18.1.0-rc4 18.1.1 18.1.2"
          - group: 37
            versions: "18.1.3 18.1.4 18.1.5"
          - group: 38
            versions: "18.1.6 18.1.7 18.1.8"
          - group: 39
            versions: "19.1.0 19.1.0-rc1 19.1.0-rc2"
          - group: 40
            versions: "19.1.0-rc3 19.1.0-rc4 19.1.1"
          - group: 41
            versions: "19.1.2 19.1.3 19.1.4"
          - group: 42
            versions: "19.1.5 19.1.6 19.1.7"
          - group: 43
            versions: "20.1.0 20.1.0-rc1 20.1.0-rc2"
          - group: 44
            versions: "20.1.0-rc3 20.1.1 20.1.2"
          - group: 45
            versions: "20.1.3 20.1.4 20.1.5"
          - group: 46
            versions: "20.1.6 20.1.7 20.1.8"
          - group: 47
            versions: "21.1.0 21.1.0-rc1 21.1.0-rc2"
          - group: 48
            versions: "21.1.0-rc3 21.1.1 21.1.2"
          - group: 49
            versions: "21.1.3 21.1.4 21.1.5"
          - group: 50
            versions: "21.1.6 21.1.7 21.1.8"
          - group: 51
            versions: "22.1.0-rc1 22.1.0-rc2 22.1.0-rc3"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push versions in group ${{ matrix.group }}
        run: |
          for version in ${{ matrix.versions }}; do
            echo "Building and pushing clang-$version..."
            docker buildx build \
              --file "dockerfiles/Dockerfile.clang-$version" \
              --tag "ghcr.io/${{ github.repository_owner }}/clang:$version" \
              --cache-from type=gha,scope=clang-$version \
              --cache-to type=gha,mode=max,scope=clang-$version \
              --push \
              .
            echo "Successfully built and pushed clang-$version"
          done
  
  tag-latest:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Tag latest version
        run: |
          LATEST_VERSION=$(grep -v '^[[:space:]]*$' versions.txt | tail -n1)
          docker pull ghcr.io/${{ github.repository_owner }}/clang:$LATEST_VERSION
          docker tag ghcr.io/${{ github.repository_owner }}/clang:$LATEST_VERSION ghcr.io/${{ github.repository_owner }}/clang:latest
          docker push ghcr.io/${{ github.repository_owner }}/clang:latest

